Auctions/Controllers/ListingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Auctions.Data;
using Auctions.Models;
using Auctions.ViewModels;
using Auctions.Services;
using System.Security.Claims;

namespace Auctions.Controllers
{

    //hhhh

    public class ListingsController : Controller
    {
        private readonly IListingServices _listingService;
        private readonly IBidService _bidService;
        private readonly ICommentService _commentService;
        private readonly IWebHostEnvironment _webHostEnviroment;

        public ListingsController(IListingServices listingService, IWebHostEnvironment webHostEnvironment, IBidService bidService, ICommentService commentService)
        {
            _listingService = listingService;
            _webHostEnviroment = webHostEnvironment;
            _bidService = bidService;
            _commentService = commentService;
        }


        public async Task<IActionResult> Index(int? pageNumber, string searchString)
        {
            var list = _listingService.GetAll();
            int pageSize = 3;
            if (!string.IsNullOrEmpty(searchString))
            {
                list = list.Where(a => a.Title.Contains(searchString));
                return View(await PaginatedList<Listing>.CreateAsync(list.Where(l => l.IsSold == false).AsNoTracking(), pageNumber ?? 1, pageSize));

            }

            return View(await PaginatedList<Listing>.CreateAsync(list.Where(l => l.IsSold == false).AsNoTracking(), pageNumber ?? 1, pageSize));
        }


        public async Task<IActionResult> MyListings(int? pageNumber)
        {
            var myListing = _listingService.GetAll();
            int pageSize = 3;

            return View("Index",await PaginatedList<Listing>.CreateAsync(myListing.Where(l => l.IdentityUserId == User.FindFirstValue(ClaimTypes.NameIdentifier)).AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        public async Task<IActionResult> MyBids(int? pageNumber)
        {
            var myBids = _bidService.GetAll();
            int pageSize = 3;

            return View(await PaginatedList<Bid>.CreateAsync(myBids.Where(l => l.IdentityUserId == User.FindFirstValue(ClaimTypes.NameIdentifier)).AsNoTracking(), pageNumber ?? 1, pageSize));
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ListingVM listing)
        {
            if (listing.Image != null)
            {
                string uploadDir = Path.Combine(_webHostEnviroment.WebRootPath, "Images");
                string fileName = listing.Image.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    listing.Image.CopyTo(fileStream);
                }

                var listObj = new Listing
                {
                    Title = listing.Title,
                    Description = listing.Description,
                    Price = listing.Price,
                    IdentityUserId = listing.IdentityUserId,
                    ImagePath = fileName,
                };
                await _listingService.Add(listObj);
                return RedirectToAction(nameof(Index));
            }
            return View(listing);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var listing = await _listingService.GetById(id);

            if (listing == null)
            {
                return NotFound();
            }

            return View(listing);
        }

        [HttpPost]
        public async Task<ActionResult> AddBid([Bind("Id,Price,ListingId,IdentityUserId")] Bid bid)
        {
            if (ModelState.IsValid)
            {
                await _bidService.Add(bid);
            }
            var listing = await _listingService.GetById(bid.ListingId);
            listing.Price = bid.Price;
            await _listingService.SaveChanges();

            return View("Details", listing);
        }

        public async Task<ActionResult> CloseBidding(int id)
        {
            var listing = await _listingService.GetById(id);
            listing.IsSold = true;
            await _listingService.SaveChanges();

            return View("Details", listing);
        }

        [HttpPost]
        public async Task<ActionResult> AddComment([Bind("Id, Content, ListingId, IdentityUserId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                await _commentService.Add(comment);
            }
            var listing = await _listingService.GetById(comment.ListingId);
            return View("Details", listing);
        }
    }
}

Auctions/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Auctions</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Auctions.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
              
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Listings" asp-action="Index">
                                <i class="fas fa-house" aria-hidden="true"></i> Active Listings
                            </a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Listings" asp-action="Create">
                                    <i class="fas fa-plus-circle" aria-hidden="true"></i> Add Listings
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Listings" asp-action="MyListings">
                                    <i class="fas fa-clipboard-list" aria-hidden="true"></i> My Listings
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Listings" asp-action="MyBids">
                                    <i class="fas fa-hand-holding-usd" aria-hidden="true"></i> My Bids
                                </a>
                            </li>
                        }

                        <li class="nav-item" style="margin:auto;">
                            <form asp-controller="Listings" asp-action="Index" method="get">
                                <input style="width: 80%; float:left; border-top-left-radius: 20px; border-bottom-left-radius: 20px; background: whitesmoke;" type="text" name="searchString" class="form-control" />
                                <button style="width:20%; float:left; border: none; background:transparent; height:40px;" type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Auctions - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>